distributable:
  url: https://github.com/symfony-cli/symfony-cli/releases/download/v{{version}}/symfony-cli-{{version}}.tar.gz
  strip-components: 1

versions:
  github: symfony-cli/symfony-cli


platforms:
  - linux/x86-64
  - linux/aarch64
  - darwin/x86-64
  - darwin/aarch64

dependencies:
  php.net: '*'

build:
  dependencies:
    gnu.org/wget: '*'
  script:
    - wget $DOWNLOAD_URL
    - $UNARCHIVE
    - mkdir -p {{prefix}}/bin
    - install ./symfony {{prefix}}/bin/symfony
    
  env:
    linux/x86-64:
      DOWNLOAD_URL: https://github.com/symfony-cli/symfony-cli/releases/download/v{{version}}/symfony-cli_linux_amd64.tar.gz
      UNARCHIVE: tar -xz -f symfony-cli_linux_amd64.tar.gz
    linux/aarch64:
      DOWNLOAD_URL: https://github.com/symfony-cli/symfony-cli/releases/download/v{{version}}/symfony-cli_linux_arm64.tar.gz
      UNARCHIVE: tar -xz -f symfony-cli_linux_arm64.tar.gz
    darwin/x86-64:
      DOWNLOAD_URL: https://github.com/symfony-cli/symfony-cli/releases/download/v{{version}}/symfony-cli_darwin_all.tar.gz
      UNARCHIVE: tar -xz -f  symfony-cli_darwin_all.tar.gz
    darwin/aarch64:
      DOWNLOAD_URL: https://github.com/symfony-cli/symfony-cli/releases/download/v{{version}}/symfony-cli_darwin_all.tar.gz
      UNARCHIVE: tar -xz -f  symfony-cli_darwin_all.tar.gz

provides:
  - bin/symfony

test: symfony -V | grep {{version}}